"""Everyday short names -> the CoFID food they should resolve to.

Keyed by the exact CoFID food name so the list is reviewable; the generator
maps names to CoFID codes and fails if a name doesn't exist or an alias is
used twice. Where a short name is ambiguous, it points at the most typical UK
preparation (e.g. "egg" -> boiled, "tea" -> with semi-skimmed milk). The app
also tries "<preparation> <description>" first, so "boiled"/"fried"/etc.
variants get their own entries.

Aliases are lowercase. The resolver also tries a singular form, so plurals
only need listing where the singular reads oddly (e.g. "chips").
"""

ALIASES = {
    # Eggs
    "Eggs, chicken, whole, boiled": ["egg", "boiled egg", "hard boiled egg", "soft boiled egg"],
    "Eggs, chicken, whole, raw": ["raw egg"],
    "Eggs, chicken, whole, fried in sunflower oil": ["fried egg"],
    "Eggs, chicken, whole, poached": ["poached egg"],
    "Eggs, chicken, scrambled, with semi-skimmed milk": ["scrambled egg", "scrambled eggs"],
    # Hot drinks
    "Coffee, infusion, average": ["coffee", "black coffee", "filter coffee", "americano", "espresso"],
    "Coffee, infusion, average, with semi-skimmed milk": ["white coffee", "coffee with milk"],
    "Coffee, instant, made up with water": ["instant coffee"],
    "Coffee, instant, made up with water and semi-skimmed milk": ["instant coffee with milk"],
    "Coffee, cappuccino, latte": ["latte", "cappuccino", "flat white"],
    "Tea, infusion, average, with semi-skimmed milk": ["tea", "cup of tea", "tea with milk", "builder's tea"],
    "Tea, black, infusion, average": ["black tea"],
    "Tea, green, infusion": ["green tea"],
    "Tea, herbal, infusion": ["herbal tea", "peppermint tea", "fruit tea"],
    # Milk and dairy
    "Milk, semi-skimmed, pasteurised, average": ["milk", "semi-skimmed milk", "semi skimmed milk"],
    "Milk, whole, pasteurised, average": ["whole milk", "full fat milk"],
    "Milk, skimmed, pasteurised, average": ["skimmed milk", "skim milk"],
    "Butter, salted": ["butter", "salted butter"],
    "Butter, unsalted": ["unsalted butter"],
    "Cheese, Cheddar, English": ["cheese", "cheddar", "cheddar cheese"],
    "Cheese, Mozzarella, fresh": ["mozzarella"],
    "Cheese, Brie, with outer rind removed": ["brie"],
    "Cheese, Feta": ["feta", "feta cheese"],
    "Cheese, Halloumi": ["halloumi"],
    "Cheese, Parmesan, fresh": ["parmesan"],
    "Cheese, cottage, plain": ["cottage cheese"],
    "Yogurt, whole milk, plain": ["yoghurt", "yogurt", "natural yoghurt", "plain yoghurt"],
    "Yogurt, Greek style, plain": ["greek yoghurt", "greek yogurt"],
    "Yogurt, low fat, plain": ["low fat yoghurt", "low fat yogurt"],
    "Yogurt, low fat, fruit": ["fruit yoghurt", "fruit yogurt"],
    "Cream, fresh, double, including Jersey cream": ["cream", "double cream"],
    "Cream, fresh, single": ["single cream"],
    "Ice cream, dairy, vanilla, soft scoop": ["ice cream", "vanilla ice cream"],
    "Custard, made up with semi-skimmed milk": ["custard"],
    # Bread and bakery
    "Bread, white, average": ["bread", "white bread", "slice of bread"],
    "Bread, brown, average": ["brown bread"],
    "Bread, wholemeal, average": ["wholemeal bread"],
    "Bread, seeded": ["seeded bread", "granary bread"],
    "Bread, white, toasted": ["toast", "white toast"],
    "Bread, wholemeal, toasted": ["wholemeal toast"],
    "Bread, brown, toasted": ["brown toast"],
    "Bagels, plain": ["bagel"],
    "Croissants": ["croissant"],
    "Crumpets, toasted": ["crumpet"],
    "Muffins, English style, white, toasted": ["english muffin"],
    "Bread, naan, retail": ["naan", "naan bread"],
    "Bread, pitta, white": ["pitta", "pitta bread"],
    "Chapatis, made without fat": ["chapati"],
    "Scones, plain, retail": ["scone"],
    "Pancakes, sweet, made with semi skimmed milk, homemade": ["pancake"],
    "Cream crackers": ["cream cracker"],
    "Oatcakes, plain, retail": ["oatcake"],
    # Breakfast cereals
    "Porridge oats, unfortified, cooked, made up with semi-skimmed milk": ["porridge", "porridge with milk"],
    "Porridge, made with water": ["porridge with water"],
    "Porridge oats, unfortified": ["oats", "porridge oats", "rolled oats"],
    "Breakfast cereal, cornflakes, fortified": ["cornflakes"],
    "Breakfast cereal, bran flakes, fortified": ["bran flakes"],
    "Breakfast cereal, wheat biscuits, Weetabix type, fortified": ["weetabix", "wheat biscuit"],
    "Muesli, Swiss style, unfortified": ["muesli"],
    # Fruit
    "Bananas, flesh only": ["banana"],
    "Apples, eating, raw, flesh and skin": ["apple"],
    "Oranges, flesh only": ["orange"],
    "Pears, raw, flesh and skin": ["pear"],
    "Grapes, average": ["grapes", "grape"],
    "Strawberries, raw": ["strawberry", "strawberries"],
    "Blueberries": ["blueberry", "blueberries"],
    "Raspberries, raw": ["raspberry", "raspberries"],
    "Kiwi fruit, flesh only, raw": ["kiwi", "kiwi fruit"],
    "Mangoes, ripe, flesh only, raw": ["mango"],
    "Citrus fruit, soft/easy peelers, flesh only": ["satsuma", "clementine", "easy peeler", "tangerine", "mandarin"],
    "Peaches, raw, flesh and skin": ["peach", "peaches"],
    "Nectarines, flesh and skin, raw": ["nectarine"],
    "Melon, flesh only, average": ["melon"],
    "Melon, watermelon, flesh only": ["watermelon"],
    "Avocado, Hass, flesh only": ["avocado"],
    "Raisins, dried": ["raisins", "raisin"],
    "Dates, dried, flesh and skin": ["dates", "date"],
    # Vegetables
    "Tomatoes, standard, raw": ["tomato", "tomatoes"],
    "Tomatoes, cherry, raw": ["cherry tomato", "cherry tomatoes"],
    "Tomatoes, canned, whole contents": ["tinned tomatoes", "chopped tomatoes"],
    "Broccoli, green, boiled in unsalted water": ["broccoli"],
    "Carrots, old, boiled in unsalted water": ["carrot", "carrots"],
    "Carrots, old, raw": ["raw carrot"],
    "Peas, frozen, boiled in unsalted water": ["peas", "pea", "garden peas"],
    "Onions, raw": ["onion"],
    "Onions, fried in sunflower oil": ["fried onion", "fried onions"],
    "Mushrooms, white, raw": ["mushroom", "mushrooms"],
    "Mushrooms, white, fried in rapeseed oil": ["fried mushroom", "fried mushrooms"],
    "Spinach, mature, raw": ["spinach"],
    "Lettuce, average, raw": ["lettuce"],
    "Cucumber, raw, flesh and skin": ["cucumber"],
    "Sweetcorn kernels, canned in water, drained": ["sweetcorn"],
    "Sweet potato, baked": ["sweet potato"],
    "Courgette, boiled in unsalted water": ["courgette"],
    "Cabbage, average, boiled in unsalted water": ["cabbage"],
    "Cauliflower, boiled in unsalted water": ["cauliflower"],
    "Beans, green, boiled in unsalted water": ["green beans", "green bean"],
    "Rocket, raw": ["rocket"],
    "Salad, green": ["salad", "green salad", "side salad"],
    "Baked beans, canned in tomato sauce": ["baked beans", "beans"],
    # Potatoes
    "Potatoes, old, boiled in unsalted water, flesh only": ["potato", "potatoes", "boiled potato", "boiled potatoes"],
    "Potatoes, new and salad, boiled in unsalted water, flesh and skin": ["new potato", "new potatoes"],
    "Potatoes, old, baked, flesh and skin": ["jacket potato", "baked potato"],
    "Potatoes, old, mashed with butter": ["mash", "mashed potato", "mashed potatoes"],
    "Potatoes, old, roasted in rapeseed oil": ["roast potato", "roast potatoes", "roasties"],
    "Potato chips, oven ready, no batter, baked": ["oven chips"],
    "Potato chips, fried in commercial oil, from takeaway fish and chip shops": ["chips", "chip shop chips"],
    "Potato crisps, fried in sunflower oil": ["crisps", "packet of crisps"],
    # Rice, pasta and grains
    "Rice, white, long grain, boiled in unsalted water": ["rice", "white rice", "boiled rice"],
    "Rice, white, basmati, boiled in unsalted water": ["basmati rice"],
    "Rice, brown, wholegrain, boiled in unsalted water": ["brown rice", "wholegrain rice"],
    "Pasta, white, dried, boiled in unsalted water": ["pasta", "penne"],
    "Pasta, white, spaghetti, dried, boiled in unsalted water": ["spaghetti"],
    "Pasta, white,  twists, fusilli, dried, boiled in unsalted water": ["fusilli"],
    "Pasta, wholewheat, spaghetti, dried, boiled in unsalted water": ["wholewheat pasta", "wholemeal pasta"],
    "Noodles, egg, medium, dried, boiled in unsalted water": ["noodles", "egg noodles"],
    "Couscous, plain, cooked": ["couscous"],
    "Lentils, red, split, dried, boiled in unsalted water": ["lentils", "red lentils"],
    "Tofu, soya bean, steamed": ["tofu"],
    # Meat
    "Bacon rashers, back, grilled": ["bacon", "back bacon", "bacon rasher"],
    "Sausages, pork, chilled, grilled": ["sausage", "sausages", "pork sausage"],
    "Ham": ["ham", "sliced ham"],
    "Chicken, breast, grilled without skin, meat only": ["chicken", "chicken breast", "grilled chicken"],
    "Chicken, meat, average, roasted": ["roast chicken"],
    "Chicken, thighs, casseroled, meat only, diced": ["chicken thigh", "chicken thighs"],
    "Beef, mince, stewed": ["mince", "beef mince"],
    "Beef, sirloin steak, grilled medium-rare, lean and fat": ["steak", "sirloin steak"],
    "Burger, beef, grilled, homemade": ["burger", "beef burger"],
    "Pork, loin chops, grilled, lean and fat": ["pork chop"],
    "Turkey, breast, fillet, grilled, meat only": ["turkey", "turkey breast"],
    # Fish
    "Salmon, farmed, flesh only, baked": ["salmon", "salmon fillet"],
    "Salmon, smoked (cold-smoked)": ["smoked salmon"],
    "Tuna, canned in brine, drained": ["tuna", "tinned tuna"],
    "Cod, flesh only, baked": ["cod"],
    "Cod, in batter, fried, takeaway": ["battered cod"],
    "Prawns, standard, purchased cooked": ["prawns", "prawn"],
    "Mackerel, flesh only, grilled": ["mackerel"],
    # Meals
    "Spaghetti bolognese, homemade": ["spaghetti bolognese", "spag bol"],
    "Chilli con carne, homemade": ["chilli", "chilli con carne"],
    "Curry, chicken tikka masala, retail, reheated": ["chicken tikka masala", "tikka masala"],
    "Pizza, cheese and tomato, retail": ["pizza", "margherita pizza"],
    "Soup, cream of tomato, canned": ["tomato soup"],
    # Spreads, oils and condiments
    "Honey": ["honey"],
    "Jam, fruit with edible seeds": ["jam"],
    "Marmalade": ["marmalade"],
    "Sugar, white": ["sugar"],
    "Peanut butter, smooth": ["peanut butter"],
    "Oil, olive": ["olive oil"],
    "Oil, vegetable, average": ["vegetable oil", "oil"],
    "Oil, sunflower": ["sunflower oil"],
    "Oil, rapeseed": ["rapeseed oil"],
    "Oil, coconut": ["coconut oil"],
    "Mayonnaise, standard, retail": ["mayonnaise", "mayo"],
    "Tomato ketchup": ["ketchup", "tomato ketchup"],
    "Houmous": ["houmous", "hummus"],
    # Snacks and sweets
    "Chocolate, milk": ["chocolate", "milk chocolate"],
    "Chocolate, plain": ["dark chocolate", "plain chocolate"],
    "Mars bar and own brand equivalents": ["mars bar"],
    "Biscuits, digestive, plain": ["digestive", "digestive biscuit"],
    "Biscuits, digestive, half coated in chocolate": ["chocolate digestive"],
    "Flapjacks, retail": ["flapjack"],
    "Doughnuts, ring, iced": ["doughnut", "donut"],
    "Brownies, chocolate, homemade": ["brownie"],
    "Cake, sponge, homemade": ["cake", "sponge cake"],
    "Popcorn, salted, retail": ["popcorn"],
    "Almonds, whole kernels": ["almonds", "almond"],
    "Peanuts, roasted and salted": ["peanuts", "peanut", "salted peanuts"],
    "Cashew nuts, kernel only, plain": ["cashews", "cashew nuts", "cashew"],
    "Walnuts, kernel only": ["walnuts", "walnut"],
    # Cold drinks
    "Orange juice, chilled": ["orange juice", "oj"],
    "Apple juice, clear, ambient and chilled": ["apple juice"],
    "Cola": ["cola", "coke", "coca cola"],
    "Cola, diet": ["diet coke", "diet cola", "coke zero"],
    "Lemonade": ["lemonade"],
    "Fruit juice drink/squash, diluted": ["squash", "orange squash"],
    # Alcohol (per 100 ml)
    "Beer, bitter, average (<4% ABV)": ["beer", "bitter", "ale"],
    "Lager, standard": ["lager"],
    "Lager, premium": ["premium lager"],
    "Wine, red": ["wine", "red wine"],
    "Wine, white, dry": ["white wine"],
    "Wine, rose, medium": ["rose wine", "rosé"],
    "Wine, white, sparkling": ["prosecco", "champagne", "sparkling wine"],
    "Cider, dry": ["cider"],
}
