"""Generates supabase/migrations/0010_cofid_aliases.sql from aliases.py.

Validates every CoFID name against the spreadsheet (so a typo fails loudly
rather than silently dropping an alias) and that no alias is used twice.

Usage:
    pip install openpyxl
    python scripts/cofid/generate_aliases_migration.py path/to/cofid.xlsx
"""

import sys
from pathlib import Path

import openpyxl

from aliases import ALIASES

OUTPUT = Path(__file__).resolve().parents[2] / "supabase/migrations/0010_cofid_aliases.sql"


def sql_text(value):
    return "'" + value.replace("'", "''") + "'"


def main(xlsx_path):
    wb = openpyxl.load_workbook(xlsx_path, read_only=True)
    code_by_name = {}
    for row in wb["1.3 Proximates"].iter_rows(min_row=4, values_only=True):
        if row[0] and row[1]:
            code_by_name.setdefault(row[1].strip(), row[0])

    errors, seen, values = [], {}, []
    for name, aliases in ALIASES.items():
        code = code_by_name.get(name)
        if code is None:
            errors.append(f"Unknown CoFID name: {name!r}")
            continue
        for alias in aliases:
            if alias != alias.strip().lower():
                errors.append(f"Alias must be lowercase and trimmed: {alias!r}")
            if alias in seen:
                errors.append(f"Alias {alias!r} used for both {seen[alias]!r} and {name!r}")
            seen[alias] = name
            values.append(f"  ({sql_text(code)}, {sql_text(alias)})")

    if errors:
        sys.exit("\n".join(errors))

    OUTPUT.write_text(
        "-- EatLog: everyday short names (\"egg\", \"black coffee\") for CoFID foods, so the\n"
        "-- resolver's alias lookup finds them. CoFID's own names (\"Eggs, chicken, whole,\n"
        "-- boiled\") never match what people say.\n"
        "-- Generated by scripts/cofid/generate_aliases_migration.py from aliases.py — edit\n"
        "-- those, not this file. Re-runnable: replaces all aliases on CoFID foods.\n\n"
        "delete from public.food_aliases\n"
        "where food_id in (select id from public.foods where source = 'cofid');\n\n"
        "insert into public.food_aliases (food_id, alias)\n"
        "select foods.id, aliases.alias\n"
        "from (values\n" + ",\n".join(values) + "\n"
        ") as aliases (source_id, alias)\n"
        "join public.foods on foods.source = 'cofid' and foods.source_id = aliases.source_id;\n"
    )
    print(f"Wrote {len(values)} aliases for {len(ALIASES)} foods to {OUTPUT}")


if __name__ == "__main__":
    main(sys.argv[1])
