"""Generates supabase/migrations/0009_cofid_foods.sql from the CoFID 2021 spreadsheet.

CoFID (McCance and Widdowson's Composition of Foods Integrated Dataset) is
published by the UK government under the Open Government Licence v3.0:
https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid

Usage:
    pip install openpyxl
    python scripts/cofid/generate_migration.py path/to/cofid.xlsx
"""

import sys
from pathlib import Path

import openpyxl

OUTPUT = Path(__file__).resolve().parents[2] / "supabase/migrations/0009_cofid_foods.sql"

# Column indexes (0-based) within each sheet; data rows start after 3 header rows.
CODE, NAME, GROUP = 0, 1, 3
PROX = {"protein": 9, "fat": 10, "carbohydrate": 11, "calories": 12, "sugar": 16, "fibre": 25}
INORG_SODIUM = 7


def parse(value):
    """CoFID uses 'Tr' for trace amounts and 'N' for unknown-but-present."""
    if value is None:
        return None
    text = str(value).strip()
    if text == "Tr":
        return 0.0
    if text in ("", "N"):
        return None
    try:
        return float(text)
    except ValueError:
        return None


def data_rows(sheet):
    for row in sheet.iter_rows(min_row=4, values_only=True):
        if row[CODE] and row[NAME]:
            yield row


def sql_num(value):
    return "null" if value is None else repr(round(value, 3))


def sql_text(value):
    return "'" + str(value).strip().replace("'", "''") + "'"


def main(xlsx_path):
    wb = openpyxl.load_workbook(xlsx_path, read_only=True)
    sodium_by_code = {row[CODE]: parse(row[INORG_SODIUM]) for row in data_rows(wb["1.4 Inorganics"])}

    values, skipped, seen_codes = [], 0, {}
    for row in data_rows(wb["1.3 Proximates"]):
        # CoFID 2021 reuses 13-669 for two different foods (aubergine, watercress),
        # so suffix repeats to keep (source, source_id) unique.
        seen_codes[row[CODE]] = seen_codes.get(row[CODE], 0) + 1
        source_id = row[CODE] if seen_codes[row[CODE]] == 1 else f"{row[CODE]}#{seen_codes[row[CODE]]}"

        nutrients = {key: parse(row[index]) for key, index in PROX.items()}
        # calories/protein/carbohydrate/fat are NOT NULL in public.foods.
        if any(nutrients[key] is None for key in ("calories", "protein", "carbohydrate", "fat")):
            skipped += 1
            continue

        # Alcoholic beverages (group Q*) are given per 100ml; everything else per 100g.
        unit = "ml" if str(row[GROUP]).startswith("Q") else "g"
        values.append(
            "  ({name}, 100, '{unit}', {calories}, {protein}, {carbohydrate}, {fat}, {fibre}, {sodium}, {sugar}, 'cofid', {code})".format(
                name=sql_text(row[NAME]),
                unit=unit,
                code=sql_text(source_id),
                sodium=sql_num(sodium_by_code.get(row[CODE])),
                **{key: sql_num(nutrients[key]) for key in PROX},
            )
        )

    OUTPUT.write_text(
        "-- EatLog: import UK reference foods from CoFID 2021 (McCance and Widdowson's\n"
        "-- Composition of Foods Integrated Dataset). Values are per 100g, or per 100ml\n"
        "-- for alcoholic beverages. Sodium in mg; fibre is AOAC fibre.\n"
        "-- Contains public sector information licensed under the Open Government Licence v3.0.\n"
        "-- Generated by scripts/cofid/generate_migration.py — edit that, not this file.\n\n"
        "create unique index if not exists foods_source_source_id_key\n"
        "  on public.foods (source, source_id);\n\n"
        "insert into public.foods\n"
        "  (name, serving_size, serving_unit, calories, protein, carbohydrate, fat, fibre, sodium, sugar, source, source_id)\n"
        "values\n" + ",\n".join(values) + "\n"
        "on conflict (source, source_id) do update set\n"
        "  name = excluded.name,\n"
        "  serving_size = excluded.serving_size,\n"
        "  serving_unit = excluded.serving_unit,\n"
        "  calories = excluded.calories,\n"
        "  protein = excluded.protein,\n"
        "  carbohydrate = excluded.carbohydrate,\n"
        "  fat = excluded.fat,\n"
        "  fibre = excluded.fibre,\n"
        "  sodium = excluded.sodium,\n"
        "  sugar = excluded.sugar;\n"
    )
    print(f"Wrote {len(values)} foods to {OUTPUT} (skipped {skipped} without core nutrients)")


if __name__ == "__main__":
    main(sys.argv[1])
