import { DayEntry, DailyGoals } from '../types';

export const mockDailyGoals: DailyGoals = {
  calories: 2000,
  protein: 130,
  carbohydrate: 250,
  fat: 70,
};

export const mockTodayEntry: DayEntry = {
  date: new Date().toISOString().split('T')[0],
  meals: [
    {
      id: '1',
      type: 'breakfast',
      items: [
        {
          id: '1-1',
          description: 'scrambled eggs',
          quantity: 2,
          unit: 'whole',
          calories: 156,
          protein: 13,
          carbohydrate: 1,
          fat: 11,
          confidence: 'high',
          estimated: false,
        },
        {
          id: '1-2',
          description: 'sourdough bread',
          quantity: 2,
          unit: 'slice',
          calories: 200,
          protein: 7,
          carbohydrate: 35,
          fat: 3,
          confidence: 'high',
          estimated: false,
        },
        {
          id: '1-3',
          description: 'butter',
          quantity: 10,
          unit: 'g',
          calories: 74,
          protein: 0,
          carbohydrate: 0,
          fat: 8,
          confidence: 'medium',
          estimated: true,
        },
        {
          id: '1-4',
          description: 'large flat white',
          quantity: 1,
          unit: 'drink',
          calories: 120,
          protein: 6,
          carbohydrate: 10,
          fat: 5,
          confidence: 'high',
          estimated: false,
        },
      ],
      totalCalories: 550,
      totalProtein: 26,
      totalCarbohydrate: 46,
      totalFat: 27,
    },
    {
      id: '2',
      type: 'lunch',
      items: [
        {
          id: '2-1',
          description: 'chicken salad',
          quantity: 1,
          unit: 'portion',
          calories: 350,
          protein: 35,
          carbohydrate: 15,
          fat: 18,
          confidence: 'medium',
          estimated: true,
        },
        {
          id: '2-2',
          description: 'apple',
          quantity: 1,
          unit: 'whole',
          calories: 95,
          protein: 0,
          carbohydrate: 25,
          fat: 0,
          confidence: 'high',
          estimated: false,
        },
      ],
      totalCalories: 445,
      totalProtein: 35,
      totalCarbohydrate: 40,
      totalFat: 18,
    },
    {
      id: '3',
      type: 'snack',
      items: [
        {
          id: '3-1',
          description: 'Greek yoghurt',
          quantity: 150,
          unit: 'g',
          calories: 97,
          protein: 10,
          carbohydrate: 4,
          fat: 5,
          confidence: 'high',
          estimated: false,
        },
        {
          id: '3-2',
          description: 'almonds',
          quantity: 30,
          unit: 'g',
          calories: 174,
          protein: 6,
          carbohydrate: 6,
          fat: 15,
          confidence: 'medium',
          estimated: true,
        },
      ],
      totalCalories: 271,
      totalProtein: 16,
      totalCarbohydrate: 10,
      totalFat: 20,
    },
  ],
  totals: {
    calories: 1266,
    protein: 77,
    carbohydrate: 96,
    fat: 65,
  },
};

export const mockHistory: DayEntry[] = [
  {
    date: '2026-09-13',
    meals: [
      {
        id: '1',
        type: 'breakfast',
        items: [
          {
            id: '1-1',
            description: 'porridge with berries',
            quantity: 1,
            unit: 'bowl',
            calories: 320,
            protein: 8,
            carbohydrate: 55,
            fat: 6,
            confidence: 'medium',
            estimated: true,
          },
        ],
        totalCalories: 320,
        totalProtein: 8,
        totalCarbohydrate: 55,
        totalFat: 6,
      },
      {
        id: '2',
        type: 'lunch',
        items: [
          {
            id: '2-1',
            description: 'tuna sandwich',
            quantity: 1,
            unit: 'whole',
            calories: 450,
            protein: 28,
            carbohydrate: 40,
            fat: 18,
            confidence: 'medium',
            estimated: true,
          },
        ],
        totalCalories: 450,
        totalProtein: 28,
        totalCarbohydrate: 40,
        totalFat: 18,
      },
      {
        id: '3',
        type: 'dinner',
        items: [
          {
            id: '3-1',
            description: 'pasta bolognese',
            quantity: 1,
            unit: 'portion',
            calories: 650,
            protein: 25,
            carbohydrate: 75,
            fat: 22,
            confidence: 'medium',
            estimated: true,
          },
        ],
        totalCalories: 650,
        totalProtein: 25,
        totalCarbohydrate: 75,
        totalFat: 22,
      },
    ],
    totals: {
      calories: 1420,
      protein: 61,
      carbohydrate: 170,
      fat: 46,
    },
  },
  {
    date: '2026-09-12',
    meals: [
      {
        id: '1',
        type: 'breakfast',
        items: [
          {
            id: '1-1',
            description: 'eggs on toast',
            quantity: 1,
            unit: 'meal',
            calories: 380,
            protein: 18,
            carbohydrate: 30,
            fat: 20,
            confidence: 'medium',
            estimated: true,
          },
        ],
        totalCalories: 380,
        totalProtein: 18,
        totalCarbohydrate: 30,
        totalFat: 20,
      },
      {
        id: '2',
        type: 'lunch',
        items: [
          {
            id: '2-1',
            description: 'soup and bread',
            quantity: 1,
            unit: 'meal',
            calories: 320,
            protein: 12,
            carbohydrate: 45,
            fat: 10,
            confidence: 'medium',
            estimated: true,
          },
        ],
        totalCalories: 320,
        totalProtein: 12,
        totalCarbohydrate: 45,
        totalFat: 10,
      },
      {
        id: '3',
        type: 'dinner',
        items: [
          {
            id: '3-1',
            description: 'salmon with vegetables',
            quantity: 1,
            unit: 'portion',
            calories: 420,
            protein: 35,
            carbohydrate: 15,
            fat: 28,
            confidence: 'medium',
            estimated: true,
          },
        ],
        totalCalories: 420,
        totalProtein: 35,
        totalCarbohydrate: 15,
        totalFat: 28,
      },
    ],
    totals: {
      calories: 1120,
      protein: 65,
      carbohydrate: 90,
      fat: 58,
    },
  },
];