const fs = require('fs');
const path = require('path');
const { withDangerousMod, withXcodeProject } = require('@expo/config-plugins');

const SOURCE_FILES = ['LogFoodIntent.swift', 'EatLogShortcuts.swift'];

// `ios/` is regenerated by `expo prebuild` (it's gitignored — see AGENTS
// notes on this repo's CNG setup), so the App Intent Swift files can't just
// live there by hand; this plugin re-copies and re-registers them on every
// prebuild instead.
function withSiriShortcutFiles(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const iosRoot = config.modRequest.platformProjectRoot;
      const targetDir = path.join(iosRoot, config.modRequest.projectName);
      for (const file of SOURCE_FILES) {
        const source = path.join(__dirname, 'native', file);
        const dest = path.join(targetDir, file);
        fs.copyFileSync(source, dest);
      }
      return config;
    },
  ]);
}

function withSiriShortcutXcodeProject(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const projectName = config.modRequest.projectName;
    const groupKey = project.findPBXGroupKey({ name: projectName });

    for (const file of SOURCE_FILES) {
      // Guard against duplicate entries if prebuild runs more than once
      // against the same project without a clean.
      const alreadyPresent = Object.values(project.hash.project.objects.PBXFileReference || {}).some(
        (entry) => entry && typeof entry.path === 'string' && entry.path.replace(/"/g, '').endsWith(file)
      );
      if (alreadyPresent) continue;

      // Path must be relative to the .xcodeproj (ios/), not to the group —
      // the files live in ios/<projectName>/, matching where they were
      // copied to in withSiriShortcutFiles above.
      project.addSourceFile(`${projectName}/${file}`, {}, groupKey);
    }

    return config;
  });
}

module.exports = function withSiriShortcut(config) {
  config = withSiriShortcutFiles(config);
  config = withSiriShortcutXcodeProject(config);
  return config;
};
